### ISSUE TITLE
TypeError: SlashCommands is not a constructor

### ISSUE THREAD

**Issue by HexM7** [Dragonizedpizza/djs-slash-commands#3]
I recently updated the package from `1.5.0` to `2.0.0` and now I'm facing this issue:
```
client.SlashCommands = new SlashCommands(client);
                       ^

TypeError: SlashCommands is not a constructor
```

**Comment by Dragonizedpizza** [comment]
> I recently updated the package from `1.5.0` to `2.0.0` and now I'm facing this issue:
> 
> ```
> client.SlashCommands = new SlashCommands(client);
>                        ^
> 
> TypeError: SlashCommands is not a constructor
> ```

how did you require SlashCommands?

**Comment by HexM7** [comment]
I tried both ways listed in the docs 
```javascript
const SlashCommands = require("djs-slash-commands");
```
And
```javascript
const { SlashCommands } = require("djs-slash-commands");
```
Both of them returned the same error. Package version `2.0.0`, it works fine when I downgrade to `1.5.0`.

**Comment by Dragonizedpizza** [comment]
> I tried both the ways listed in the docs
> 
> ```js
> const SlashCommands = require("djs-slash-commands");
> ```
> 
> And
> 
> ```js
> const { SlashCommands } = require("djs-slash-commands");
> ```
> 
> Both of them returned the same error. Package version `2.0.0`, it works fine when I downgrade to `1.5.0`.

I made a mistake in the README, could you try installing `2.0.1` via `npm i djs-slash-commands@2.0.1`, and reading the README again? Also, the fix to your issue is requiring it via:

```js
const { SlashCommandHandler } = require("djs-slash-commands");

// Or, 

const SlashCommands = require("djs-slash-commands").SlashCommandHandler;
```

**Comment by HexM7** [comment]
This fixed the issue. Thanks!
