### ISSUE TITLE
slashCreate event is not fired in version 2.0.1

### ISSUE THREAD

**Issue by HexM7** [Dragonizedpizza/djs-slash-commands#4]
I recently upgraded the package from `1.5.0` to `2.0.2` and now the `slashCreate` event is not triggered, using a slash command returns `Interaction failed`.

Start of the code:
```javascript
const { SlashCommandHandler } = require("djs-slash-commands");
client.SlashCommands = new SlashCommandHandler(client);

. . .


client.SlashCommands.listen();
client.on("slashCreate", async (interaction) => {
  console.log('ok')
  client.slashHandler.slash(client, interaction);
});
```
It works fine in the older version `1.5.0`

**Comment by Dragonizedpizza** [comment]
fixed, try 2.0.3

**Comment by HexM7** [comment]
Still not working :(

**Comment by Dragonizedpizza** [comment]
that's weird. I just tried it, and it works for me

**Comment by HexM7** [comment]
Do we still need to use `client.SlashCommands.listen()`?

**Comment by Dragonizedpizza** [comment]
You do. Could you show your entire code?

**Comment by HexM7** [comment]
```javascript
const Discord = require("discord.js");
const client = new Discord.Client();
const { SlashCommandHandler } = require("djs-slash-commands");
client.SlashCommands = new SlashCommandHandler(client);

async function initSlash(client) {
  const commandFiles = fs.readdirSync('./slashCommands/').filter(file => file.endsWith('.js'));
  for (const file of commandFiles) {
      const command = require(`./slashCommands/${file}`);
      var obj = {
          name: command.name,
          description: command.description,
          options: command.commandOptions
        };
      await client.SlashCommands.add(obj, "GUILD_ID");
}


};
client.on('ready', async msg => {
  await initSlash(client);
});


//The event below dosen't get triggered
// also tried with 'client.SlashCommands.listen()'
client.on("slashCreate", async (interaction) => {
  console.log('ok')
  client.slashHandler.slash(client, interaction);
});

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/125282277-7ca6ef00-e317-11eb-9e76-092cf808ab02.png)
isn't a function

[Uploading 40306_1.pdf…]()
try having the listen function in the ready event

**Comment by HexM7** [comment]
```client.slashHandler.slash(client, interaction)```
It's my custom function to call modules stored in files outside the directory, and it's in no-way causing the error as its an entire different collection having different name. 

> try having the listen function in the ready event

I have already tried that

**Comment by Dragonizedpizza** [comment]
> `client.slashHandler.slash(client, interaction)`
> It's my custom function to call modules stored in files outside the directory, and it's in no-way causing the error as its an entire different collection having different name.
> 
> > try having the listen function in the ready event
> 
> I have already tried that

could you try it again, perhaps with the v2.0.3 version

**Comment by HexM7** [comment]
Still not working with v2.0.3

**Comment by Dragonizedpizza** [comment]
> Still not working with v2.0.3

code?

**Comment by HexM7** [comment]
The code is almost the same:
```javascript 
const Discord = require("discord.js");
const client = new Discord.Client();
const { SlashCommandHandler } = require("djs-slash-commands");
client.SlashCommands = new SlashCommandHandler(client);

async function initSlash(client) {
  const commandFiles = fs.readdirSync('./slashCommands/').filter(file => file.endsWith('.js'));
  for (const file of commandFiles) {
      const command = require(`./slashCommands/${file}`);
      var obj = {
          name: command.name,
          description: command.description,
          options: command.commandOptions
        };
      await client.SlashCommands.add(obj, "GUILD_ID");
}


};
client.on('ready', async msg => {
  await initSlash(client);
  client.SlashCommands.listen();
});


client.on("slashCreate", async (interaction) => {
  console.log('ok'); //Event not getting triggered
});
```

**Comment by Dragonizedpizza** [comment]
That's wierd. Could you add me on Discord (Dɾαɠσɳιȥҽԃριȥȥα#0317) and show
me an example?

**Comment by HexM7** [comment]
Sent you a friend request as "VelociRaptor#5757"

**Comment by Dragonizedpizza** [comment]
I seem to have found the issue. `npm i djs-slash-commands@2.1.0`

**Comment by HexM7** [comment]
Thank you, the issue is fixed now. 🎉
