### ISSUE TITLE
DiscordAPIError: Unknown interaction when trying to reply to an interaction

### ISSUE THREAD

**Issue by HexM7** [Dragonizedpizza/djs-slash-commands#5]
Version: `2.1.0`
When I try to reply to an interaction
```javascript
interaction.reply('Message');
```
The API throws an error:
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async SlashCommandInteraction.reply (node_modules\djs-slash-commands\src\structures\CommandInteraction.js:224:5) {
  method: 'post',
  path: '/interactions/TOKEN_HIDDEN_DUE_TO_SECURITY_REASONS/callback',
  code: 10062,
  httpStatus: 404
}
```

The same code works fine when I send the message to the interaction channel instead of replying to the interaction:
```javascript
interaction.channel.send('Message') //This works fine
```

**Comment by Dragonizedpizza** [comment]
> Version: `2.1.0`
> When I try to reply to an interaction
> 
> ```js
> interaction.reply('Message');
> ```
> 
> The API throws an error:
> 
> ```
> DiscordAPIError: Unknown interaction
>     at RequestHandler.execute (node_modules\discord.js\src\rest\RequestHandler.js:154:13)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async RequestHandler.push (node_modules\discord.js\src\rest\RequestHandler.js:39:14)
>     at async SlashCommandInteraction.reply (node_modules\djs-slash-commands\src\structures\CommandInteraction.js:224:5) {
>   method: 'post',
>   path: '/interactions/TOKEN_HIDDEN_DUE_TO_SECURITY_REASONS/callback',
>   code: 10062,
>   httpStatus: 404
> }
> ```
> 
> The same code works fine when I send the message to the interaction channel instead of replying to the interaction:
> 
> ```js
> interaction.channel.send('Message') //This works fine
> ```

does this happen with all interactions?

**Comment by HexM7** [comment]
Yes, only when I try to `reply` to an interaction.

**Comment by Dragonizedpizza** [comment]
https://github.com/Dragonizedpizza/djs-slash-commands/commit/bc828fa0060b90c22a0b4acb269514d8f7a4b22c | version `2.3.0`

**Comment by HexM7** [comment]
Did you publish `2.3.0` on npm? I'll try again after few a hours
![Screenshot (186)](https://user-images.githubusercontent.com/77036902/125793817-bac6762e-b13b-4872-be49-7291ea32acad.png)

**Comment by Dragonizedpizza** [comment]
forgot about publishing it :sweat_smile:, try now

**Comment by Dragonizedpizza** [comment]
By the way, interaction.args is no longer a thing, being replaced by interaction.options.

**Comment by Dragonizedpizza** [comment]
and you no longer require doing SlashCommands.listen();

**Comment by zignis** [comment]
Thanks, the issue has been fixed 🎉
