### ISSUE TITLE
Events never emitted

### ISSUE THREAD

**Issue by KeyboardRage** [Dragonizedpizza/djs-slash-commands#7]
It seems like `SlashCommandHandler.listen()` is never called, nor shown anywhere in the documentation. Without it `client.on("slashCreate")` is never emitted.

**Comment by Dragonizedpizza** [comment]
https://github.com/Dragonizedpizza/djs-slash-commands/commit/bc828fa0060b90c22a0b4acb269514d8f7a4b22c | version `2.3.0`
