### ISSUE TITLE
TypeError: Cannot read property 'ephemeral' of undefined

### ISSUE THREAD

**Issue by zignis** [Dragonizedpizza/djs-slash-commands#9]
The command responds successfully but whenever I call a command, a warning is thrown into the terminal:
```
TypeError: Cannot read property 'ephemeral' of undefined
  at SlashCommandInteraction.reply (node_modules\djs-slash-commands\src\structures\CommandInteraction.js:240:30)
```

**Comment by DragonZV** [comment]
Invalid Interaction occurs when you don't reply to the interaction within three seconds, and I'm not sure why the error occurs.

**Comment by DragonZV** [comment]
Could you send me node_modules\djs-slash-commands\src\structures\CommandInteraction.js:240:30

**Comment by zignis** [comment]
`CommandInteraction.js` at line `240`:
```javascript
    this.epehemeral = options["ephemeral"] ? true : false;
```
Version `2.3.0`

**Comment by DragonZV** [comment]
try 2.3.1

**Comment by zignis** [comment]
Fixed 🎉
